version: '3.4'

services:
  avina:
    image: avinalocationacr.azurecr.io/avina
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    environment:
      NODE_ENV: production
    ports:
      - 9999:9999
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db