version: '3.4'

services:
  sightplusplus:
    image: locationserver.azurecr.io/sightplusplus
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
      - 7979:7979
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
