version: '3.4'

services:
  sightplusplus:
    image: sightplusplus
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
      - 7979:7979
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
