# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Create env file
      run: |
        touch .env
        echo DATABASE_HOST=localhost >> .env
        echo DATABASE_PORT=27017 >> .env
        echo DATABASE_NAME=SightPlusPlus >> .env
        echo UDP_SERVER_HOST=localhost >> .env
        echo UDP_PORT=7979 >> .env
        echo ORG_HOST=localhost >> .env
        echo ORG_PORT=5000 >> .env
        echo DEVICE_CRON="0 * * * *" >> .env
        echo "KB_HOST=$KB_HOST" >> .env
        echo "KB_ENDPOINT_KEY=$KB_ENDPOINT_KEY" >> .env
        echo "KB_ID=$KB_ID" >> .env
      env:
        KB_HOST: ${{secrets.KB_HOST}}
        KB_ENDPOINT_KEY: ${{secrets.KB_ENDPOINT_KEY}}
        KB_ID: ${{secrets.KB_ID}}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: sudo docker run --name mongo -d -p 27017:27017 mongo
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test --abort-on-uncaught-exception
