# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: sightPlusPlus-location   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.x'                # set this to the node version to use
  DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
  DATABASE_PORT: 27017
  DATABASE_NAME: SightPlusPlus
  UDP_SERVER_HOST: localhost
  UDP_PORT: 7979
  DEVICE_CRON: '0 * * * *'
  KB_HOST: ${{ secrets.KB_HOST }}
  KB_ENDPOINT_KEY: ${{ secrets.KB_ENDPOINT_KEY }}
  KB_ID: ${{ secrets.KB_ID }}

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm install, build
        run: |
          # Build and test the project, then
          # deploy to Azure Web App.
          npm install
          npm run build --if-present

      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9FBA4543F6E84907A831CFA235A90A94 }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}